### ISSUE TITLE
Missing full help text

### ISSUE THREAD

**Issue by bjornfor** [ryansuchocki/microscheme#17]
It would be nice to have microscheme print its own (full) help text, so that one doesn't have to open README or something like that just to know what the command line flags are for:

```
$ microscheme 
Microscheme 0.9.1, (C) Ryan Suchocki
Usage: microscheme [-aucvrio] [-m model] [-d device] [-w filename] [-t rounds] program[.ms]
```

I also tried -h and --help, but those are not implemented.

**Comment by bjornfor** [comment]
By "full", I'm just referring to command line option description.

**Comment by ryansuchocki** [comment]
Done. It will now show full help if '-h' passed, or if no inputs given...

**Comment by bjornfor** [comment]
Thanks!
