### ISSUE TITLE
Add command line option to override programmer

### ISSUE THREAD

**Issue by rekado** [ryansuchocki/microscheme#20]
I have an AVRISPmkII and would like to use it rather than a plain serial connection.  `avrdude` supports this programmer, but microscheme hardcodes the programmer by tying the programmer to the model in `src/models.c`.

It would be nice if I could directly pass flags through to avrdude, or --- more specifically --- override the programmer.

**Comment by ryansuchocki** [comment]
Done. Can you test this, I don't have time...

**Comment by rekado** [comment]
Thanks!  Works for me.
