### ISSUE TITLE
Exception in loop when using for-each

### ISSUE THREAD

**Issue by rekado** [ryansuchocki/microscheme#22]
When I run this on an ATmega32, after just a few seconds an exception is signaled (different exceptions dependent on what happens in the lambda).

~~~
(define (loop)
  (for-each
   (lambda (_) 1) (list 1))
  (pause 1))

(forever loop)
~~~

It doesn't matter what value is returned in the lambda.  The same behaviour can be observed when I replace the lambda with a procedure that's defined outside of the loop.

Seems that there's something wrong with `for-each`.

**Comment by ryansuchocki** [comment]
See http://microscheme.org/documentation#memman

**Comment by rekado** [comment]
Bummer.  Are there any plans to add garbage collection?  Or to pin lambdas automatically?

**Comment by ryansuchocki** [comment]
Either of those would be brilliant, and I have spent a lot of time thinking about them, but they are not easy. It seems garbage collection will require deep changes to the runtime system, and lambda lifting might require equally deep changes to the compiler architecture. Honestly, I don't know if I'll ever have the time to do it myself, but then, that's the point of open-sourcing isn't it! ;-)

**Comment by ryansuchocki** [comment]
To clarify: it's not just a time issue... I haven't really worked out *how* to do it :)
