### ISSUE TITLE
serial-init on UNO leads to malformed output from serial-write.

### ISSUE THREAD

**Issue by jellelicht** [ryansuchocki/microscheme#30]
When running the example `serial.ms` program (or any program using serial output for that matter) on the UNO rev3, I get weird output (mostly question marks, sometimes mis-matched symbols). By linking to an external C file that uses avr libc's `#include <util/setbaud.h>` to initialize the serial communication, i.c.w. microscheme's FFI, I do get the results I want. In this setting I omit any call to `serial init` (in my case `(serial-init 96)`).

**Comment by ryansuchocki** [comment]
I haven't been able to re-produce this on my UNO R3.
