### ISSUE TITLE
Reading current time

### ISSUE THREAD

**Issue by nico202** [ryansuchocki/microscheme#44]
Hi, I'm checking out this project and I really like it.  I wanted to re-write the DHT (temeprature sensor) library in it, but I could not find a way to get the current time (something like the [micros()](https://www.arduino.cc/reference/en/language/functions/time/micros/) or millis() functions).

Is there a way right now?

Thanks

**Comment by glv2** [comment]
Currently keeping track of time is not implemented. However it is possible to implement the DHT protocol without it. I did it for the DHT11 sensor in https://github.com/glv2/microscheme/tree/dht (tested with an Arduino Nano).

@ryansuchocki where do you think the implementation of generic protocols (TWI/I2C, SPI, etc) or custom protocols (DHT, sensors, etc) should go? In "src/stdlib.ms", in the "examples" directory, in a "libraries" directory, or in another repository?

**Comment by nico202** [comment]
> However it is possible to implement the DHT protocol without it.

Yes I realized it after asking the question, but I still need time to measure the temperature change over time for my project.

> I did it for the DHT11 sensor in https://github.com/glv2/microscheme/tree/dht (tested with an Arduino Nano).
Thanks, I'll try to make it work with the DHT21 and eventually open a PR!

**Comment by ryansuchocki** [comment]
Implementations of generic and specific protocols should go in the top level "libraries" directory which I've just created. Thanks.
