### ISSUE TITLE
Worth considering a new release (as in Git tag)?

### ISSUE THREAD

**Issue by fabionatali** [ryansuchocki/microscheme#47]
Hi, do you think we could have a new Git tag released for the current master (or any recent commit)?

The reason I'm asking might be a bit niche - I'd like to update Microscheme's Guix package, which is still at 0.9.3 (2016).

Guix packages can be created out of any commit, of course, regardless of Git tags - but a tag might make the package approval process marginally easier (just my wild guess!).

For clarity, I'm not suggesting/requesting any new functionality, just a Git tag to possibly be created. If this is not the right time (in the project lifecycle/roadmap) for a new tag, please ignore this request.

Sorry, not sure this was the right place to suggest this. Thanks for Microscheme!!

**Comment by ryansuchocki** [comment]
No problem. Done.

**Comment by fabionatali** [comment]
Oh wow - that was a speedy :rocket: response!! Thanks so much! :pray:
